-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Director General"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    laboratorio_id bigint NOT NULL,
    CONSTRAINT "Director General_pkey" PRIMARY KEY (id),
    CONSTRAINT "Director General_laboratorio_id_key" UNIQUE (laboratorio_id)
);

CREATE TABLE IF NOT EXISTS public."Laboratorio"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Laboratorio_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Productos"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    f_fabricacion date NOT NULL,
    p_costo numeric(12, 2) NOT NULL,
    p_venta numeric(12, 2) NOT NULL,
    laboratorio_id bigint NOT NULL,
    CONSTRAINT "Productos_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Director General"
    ADD CONSTRAINT "Director General_laboratorio_id_8a4b7266_fk_Laboratorio_id" FOREIGN KEY (laboratorio_id)
    REFERENCES public."Laboratorio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Director General_laboratorio_id_key"
    ON public."Director General"(laboratorio_id);


ALTER TABLE IF EXISTS public."Productos"
    ADD CONSTRAINT "Productos_laboratorio_id_34299e91_fk_Laboratorio_id" FOREIGN KEY (laboratorio_id)
    REFERENCES public."Laboratorio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "Productos_laboratorio_id_34299e91"
    ON public."Productos"(laboratorio_id);

END;